steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_GTM_ID=$_NEXT_PUBLIC_GTM_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/storybook-ai:$COMMIT_SHA'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storybook-ai:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'storybook-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/storybook-ai:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

substitutions:
    _NEXT_PUBLIC_FIREBASE_API_KEY: ''
    _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ''
    _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ''
    _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ''
    _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ''
    _NEXT_PUBLIC_FIREBASE_APP_ID: ''
    _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ''
    _NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ''
    _NEXT_PUBLIC_GTM_ID: ''

options:
    logging: CLOUD_LOGGING_ONLY
