import { useTranslations } from 'next-intl';
import Link from 'next/link';
import Image from 'next/image';

export default function TermsOfService() {
    const t = useTranslations('HomePage');

    return (
        <main className="min-h-screen relative flex flex-col items-center px-4 py-24 sm:p-8 overflow-hidden font-sans">
            {/* Background Image */}
            <div className="absolute inset-0 z-0">
                <Image
                    src="/images/landing-bg.png"
                    alt="Kidoredo Background"
                    fill
                    priority
                    quality={80}
                    className="object-cover object-center"
                />
                <div className="absolute inset-0 bg-black/40" />
            </div>

            <div className="z-10 w-full max-w-4xl bg-white/10 backdrop-blur-xl rounded-3xl p-8 md:p-12 shadow-2xl border border-white/20 text-white">
                <Link href="/" className="mb-8 inline-block text-yellow-400 hover:text-yellow-300 font-semibold transition-colors">
                    &larr; {t('title')}
                </Link>
                <h1 className="text-4xl md:text-5xl font-extrabold mb-8 text-white drop-shadow-md">Terms of Service</h1>

                <div className="prose prose-lg prose-invert max-w-none text-blue-50/90 leading-relaxed font-medium">
                    <p className="text-white/60 mb-8 border-b border-white/20 pb-4"><strong>Last Updated:</strong> February 2026</p>

                    <h2 className="text-2xl font-bold mt-10 mb-5 text-white drop-shadow-sm">1. Acceptance of Terms</h2>
                    <p>By accessing or using Kidoredo, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

                    <h2 className="text-2xl font-bold mt-10 mb-5 text-white drop-shadow-sm">2. Description of Service</h2>
                    <p>Kidoredo provides a platform for generating personalized, AI-powered stories for children. We utilize artificial intelligence to create text and images based on your inputs.</p>

                    <h2 className="text-2xl font-bold mt-10 mb-5 text-white drop-shadow-sm">3. User Responsibilities</h2>
                    <p>You are responsible for the inputs you provide. You agree not to input any content that is illegal, offensive, or violates the rights of others.</p>

                    <h2 className="text-2xl font-bold mt-10 mb-5 text-white drop-shadow-sm">4. AI-Generated Content</h2>
                    <p>The stories and images are generated by artificial intelligence. While we strive for high quality and appropriate content, Kidoredo cannot guarantee the absolute accuracy or appropriateness of every generated output.</p>

                    <h2 className="text-2xl font-bold mt-10 mb-5 text-white drop-shadow-sm">5. Contact</h2>
                    <p>Please contact us at <a href="mailto:hello@kidoredo.com" className="text-yellow-400 hover:text-yellow-300 transition-colors font-bold">hello@kidoredo.com</a> with any questions regarding these Terms.</p>
                </div>
            </div>
        </main>
    );
}

